### ISSUE TITLE
CNV pipeline : chromosomes not processed

### ISSUE THREAD

**Issue by Romeo1-1** [eudoraleer/Ursa#1]
Hello and thank you for this wonderful & very user friendly package ! Especially for scCNV it's very hard to find functional and easy-to-use packages.

I have an issue with the aforenamed CNV pipeline (and I didn't try the others yet). I'm trying to run it on 10X CNV datas, processed with CellRanger DNA. My files are :
- mappable_regions.bed
- node_cnv_calls.bed
- per_cells_summary_metrix.csv

When I run the pipeline, I only get results from chr X and chr Y. At first I fought it was a "chromosome name" problem (in my files, the chromosome name was "chr1", "chr2" etc) but even after renaming the chr names to "1", "2" etc it didn't help. I tried to look into the R script but I didn't find any easy answer.

These are the results i get from the pipeline. And when I look at the RDS files in the output, I only have chrX and chrY.

![Output2](https://user-images.githubusercontent.com/101837631/188958278-4b411d17-fe66-460b-959c-3b1265292327.png)

![Output1](https://user-images.githubusercontent.com/101837631/188958275-7b744d46-3017-4007-8265-cea18bdab471.png)

![image](https://user-images.githubusercontent.com/101837631/188958562-ce7c3b53-9256-43da-9b9a-f34ab2ed18ff.png)

Thank you in advance for your help

**Comment by Romeo1-1** [comment]
Just a heads up, I tried with the 10X example dataset and it worked perfectly. I also tried with other samples from different patients & experiments and I get the exact same type of plot (with only chrx & y). Do you have, by any chance, any idea why it does that with my datasets ?

Thanks in advance

**Comment by eudoraleer** [comment]
> Just a heads up, I tried with the 10X example dataset and it worked perfectly. I also tried with other samples from different patients & experiments and I get the exact same type of plot (with only chrx & y). Do you have, by any chance, any idea why it does that with my datasets ?
> 
> Thanks in advance

Dear Romeo,

Thank you for using our software!! So sorry that I was very busy for the past few weeks. I wonder if you could show me the first few lines of the following three files:

mappable_regions.bed
node_cnv_calls.bed
per_cells_summary_metrix.csv

Also, what reference are you using?

Best,
Lu

**Comment by Romeo1-1** [comment]
Hello, no worries at all !

I could also send you the whole files via email if that can help us! My reference was h38, furnished by CellRanger

```
mappable_regions.bed
#cellranger-dna 1.1.0
#reference genome: refdata-GRCh38-1.0.0/
#chrom	start	end
chr1	780000	1700000
chr1	1720000	2660000
chr1	2780000	12860000
chr1	13100000	13120000
chr1	13220000	13240000
chr1	13320000	16540000
chr1	16600000	16640000
chr1	16860000	25320000
chr1	25340000	25360000
chr1	25380000	39760000
chr1	39780000	46880000
chr1	46900000	103600000
chr1	103760000	108220000
chr1	108320000	108380000
chr1	108480000	120000000
chr1	120120000	120140000
chr1	120160000	120180000
```

```
node_cnv_calls.bed
cellranger-dna 1.1.0
#reference genome: refdata-GRCh38-1.0.0/
#chrom	start	end	id	copy_number	event_confidence
chr1	780000	800000	1238	6	1
chr1	780000	800000	1277	3	5
chr1	780000	800000	1307	8	0
chr1	780000	800000	1395	3	5
chr1	780000	800000	1411	3	5
chr1	780000	800000	1432	3	5
chr1	780000	800000	1456	9	0
chr1	780000	800000	222	18	0
chr1	780000	800000	299	18	0
chr1	780000	800000	604	9	0
chr1	780000	800000	623	33	0
chr1	780000	820000	1381	1	13
chr1	780000	820000	1429	4	2
chr1	780000	820000	1494	2	8
chr1	780000	820000	1546	2	5
chr1	780000	820000	1561	2	15
chr1	780000	820000	1566	2	3

```


```
per_cells_summary_metrix.csv

barcode,cell_id,total_num_reads,num_unmapped_reads,num_lowmapq_reads,num_duplicate_reads,num_mapped_dedup_reads,frac_mapped_duplicates,effective_depth_of_coverage,effective_reads_per_1Mbp,raw_mapd,normalized_mapd,raw_dimapd,normalized_dimapd,mean_ploidy,ploidy_confidence,is_high_dimapd,is_noisy,est_cnv_resolution_mb
AAACCTGAGGCATTGG-1,0,199404,1739,17345,3843,176477,0.01927243184690377,0.008567633801242274,57,0.2382765236420624,0.2382765236420624,0.9191739444818208,0.9191739444818208,1.8727702783084557,7,0,0,3.801171875000007
AAACGGGAGGCATTTC-1,1,368258,6050,42775,7231,312202,0.01963569019546079,0.015213967870667592,101,0.18867811260485906,0.18867811260485906,0.9435430578405056,0.9435430578405056,1.8249270412697969,13,0,0,2.476464843750004
AAACGGGCAGGCCGTT-1,2,141832,1470,14063,2897,123402,0.02042557391843872,0.006067334792395822,40,0.29457579454014404,0.29457579454014404,0.9619301504696892,0.9619301504696892,1.8893905033876477,29,0,0,5.614453125000011
AAAGATGAGCTTCAGT-1,3,283236,2347,27562,5774,247553,0.020385826660452768,0.012141185207161004,80,0.2130048958979687,0.2130048958979687,0.9607697419023016,0.9607697419023016,1.924672397379179,14,0,0,3.111035156250005
AAAGATGCAGGTCAAG-1,4,201920,1991,21186,4088,174655,0.020245641838351824,0.008630230986888712,57,0.24025879756881266,0.24025879756881266,0.9179163913088424,0.9179163913088424,1.8172847455017531,12,0,0,3.847412109375008
AAAGCAACAAGCTACT-1,5,265682,2475,26608,5500,231099,0.020701440067449055,0.011352446809123251,75,0.21460300623777648,0.21460300623777648,0.9387324297389572,0.9387324297389572,1.948456349539564,-2,0,0,3.1550292968750053
AAAGCAACATTATCGG-1,6,186314,2205,19260,3918,160931,0.02102901553291755,0.007908931644156928,52,0.2705498714193894,0.2705498714193894,1.002964076864443,1.002964076864443,1.9054035136837684,7,0,0,4.819384765625011
AAAGCAAGTACCAACT-1,7,257902,3833,29276,4907,219886,0.01902660700576188,0.010753358613904952,71,0.20929887597656732,0.20929887597656732,0.8904177827538724,0.8904177827538724,1.8052071668533034,14,0,0,2.982031250000005
AAAGTAGAGAGACGAA-1,8,179968,1888,17566,3675,156839,0.020420296941678517,0.007675356523056565,51,0.2435681728384565,0.2435681728384565,0.8918871767964626,0.8918871767964626,1.845327416780985,25,0,0,3.9434082031250073
AAAGTAGAGCCGGTAA-1,9,143738,1747,13705,2843,125443,0.019779042424411083,0.006124784111804904,41,0.29841323168725303,0.29841323168725303,0.9805536203473828,0.9805536203473828,1.8488553571803503,23,0,0,5.741357421875011
AAAGTAGCATCCACGG-1,10,219044,2334,21335,4367,191008,0.019936633735687808,0.009352377729667244,62,0.2219555930296248,0.2219555930296248,0.886119897530825,0.886119897530825,1.8399759257056079,-3,0,0,3.326074218750006
AAAGTAGTCTGTATGG-1,11,201076,2412,17130,3877,177657,0.01928126678469832,0.008577818468292442,58,0.23192375930546155,0.23192375930546155,0.8987765062553958,0.8987765062553958,1.8695655216819238,5,0,0,3.6129394531250063
AAAGTAGTCTTCACGC-1,12,306588,2728,29061,5802,268997,0.018924419742455675,0.013065888084613456,87,0.1855875456556801,0.1855875456556801,0.8651298666321601,0.8651298666321601,1.8871088528215787,4,0,0,2.4009277343750037
AAATGCCTCTGCTACC-1,13,388508,3762,37700,7592,339454,0.019541425144398567,0.01658867741062077,110,0.18862021146234528,0.18862021146234528,0.9791540468075924,0.9791540468075924,1.9183010653339494,-2,0,0,2.490820312500004
AACCATGCAACGCGTC-1,14,252458,2877,26803,4459,218319,0.017662343835410245,0.01063741764388676,71,0.19531869262779145,0.19531869262779145,0.8302301340525406,0.8302301340525406,3.3243457018262252,17,0,0,2.895605468750005
AACCATGCATGAATGA-1,15,73548,1256,6019,1509,64764,0.020517213248490783,0.0030901137268241137,21,0.3967454164992783,0.3967454164992783,0.9496714389706746,0.9496714389706746,1.8451671145448438,17,0,0,9.616601562500023
AACGTTGAGAAACCAT-1,16,88244,745,9669,1611,76219,0.018256198721726125,0.0038033315218422275,25,0.3100328286434906,0.3100328286434906,0.7943890490416823,0.7943890490416823,1.8477014912839318,24,0,0,6.084472656250012
```

**Comment by eudoraleer** [comment]
> 

Dear Romeo,

Thank you for the information! I will take a look, also, I did not receive your email, can you send that again to lu.pan@ki.se, thanks!

Best,
Lu

**Comment by eudoraleer** [comment]
> Hello, no worries at all !
> 
> I could also send you the whole files via email if that can help us! My reference was h38, furnished by CellRanger
> 
> ```
> mappable_regions.bed
> #cellranger-dna 1.1.0
> #reference genome: refdata-GRCh38-1.0.0/
> #chrom	start	end
> chr1	780000	1700000
> chr1	1720000	2660000
> chr1	2780000	12860000
> chr1	13100000	13120000
> chr1	13220000	13240000
> chr1	13320000	16540000
> chr1	16600000	16640000
> chr1	16860000	25320000
> chr1	25340000	25360000
> chr1	25380000	39760000
> chr1	39780000	46880000
> chr1	46900000	103600000
> chr1	103760000	108220000
> chr1	108320000	108380000
> chr1	108480000	120000000
> chr1	120120000	120140000
> chr1	120160000	120180000
> ```
> 
> ```
> node_cnv_calls.bed
> cellranger-dna 1.1.0
> #reference genome: refdata-GRCh38-1.0.0/
> #chrom	start	end	id	copy_number	event_confidence
> chr1	780000	800000	1238	6	1
> chr1	780000	800000	1277	3	5
> chr1	780000	800000	1307	8	0
> chr1	780000	800000	1395	3	5
> chr1	780000	800000	1411	3	5
> chr1	780000	800000	1432	3	5
> chr1	780000	800000	1456	9	0
> chr1	780000	800000	222	18	0
> chr1	780000	800000	299	18	0
> chr1	780000	800000	604	9	0
> chr1	780000	800000	623	33	0
> chr1	780000	820000	1381	1	13
> chr1	780000	820000	1429	4	2
> chr1	780000	820000	1494	2	8
> chr1	780000	820000	1546	2	5
> chr1	780000	820000	1561	2	15
> chr1	780000	820000	1566	2	3
> ```
> 
> ```
> per_cells_summary_metrix.csv
> 
> barcode,cell_id,total_num_reads,num_unmapped_reads,num_lowmapq_reads,num_duplicate_reads,num_mapped_dedup_reads,frac_mapped_duplicates,effective_depth_of_coverage,effective_reads_per_1Mbp,raw_mapd,normalized_mapd,raw_dimapd,normalized_dimapd,mean_ploidy,ploidy_confidence,is_high_dimapd,is_noisy,est_cnv_resolution_mb
> AAACCTGAGGCATTGG-1,0,199404,1739,17345,3843,176477,0.01927243184690377,0.008567633801242274,57,0.2382765236420624,0.2382765236420624,0.9191739444818208,0.9191739444818208,1.8727702783084557,7,0,0,3.801171875000007
> AAACGGGAGGCATTTC-1,1,368258,6050,42775,7231,312202,0.01963569019546079,0.015213967870667592,101,0.18867811260485906,0.18867811260485906,0.9435430578405056,0.9435430578405056,1.8249270412697969,13,0,0,2.476464843750004
> AAACGGGCAGGCCGTT-1,2,141832,1470,14063,2897,123402,0.02042557391843872,0.006067334792395822,40,0.29457579454014404,0.29457579454014404,0.9619301504696892,0.9619301504696892,1.8893905033876477,29,0,0,5.614453125000011
> AAAGATGAGCTTCAGT-1,3,283236,2347,27562,5774,247553,0.020385826660452768,0.012141185207161004,80,0.2130048958979687,0.2130048958979687,0.9607697419023016,0.9607697419023016,1.924672397379179,14,0,0,3.111035156250005
> AAAGATGCAGGTCAAG-1,4,201920,1991,21186,4088,174655,0.020245641838351824,0.008630230986888712,57,0.24025879756881266,0.24025879756881266,0.9179163913088424,0.9179163913088424,1.8172847455017531,12,0,0,3.847412109375008
> AAAGCAACAAGCTACT-1,5,265682,2475,26608,5500,231099,0.020701440067449055,0.011352446809123251,75,0.21460300623777648,0.21460300623777648,0.9387324297389572,0.9387324297389572,1.948456349539564,-2,0,0,3.1550292968750053
> AAAGCAACATTATCGG-1,6,186314,2205,19260,3918,160931,0.02102901553291755,0.007908931644156928,52,0.2705498714193894,0.2705498714193894,1.002964076864443,1.002964076864443,1.9054035136837684,7,0,0,4.819384765625011
> AAAGCAAGTACCAACT-1,7,257902,3833,29276,4907,219886,0.01902660700576188,0.010753358613904952,71,0.20929887597656732,0.20929887597656732,0.8904177827538724,0.8904177827538724,1.8052071668533034,14,0,0,2.982031250000005
> AAAGTAGAGAGACGAA-1,8,179968,1888,17566,3675,156839,0.020420296941678517,0.007675356523056565,51,0.2435681728384565,0.2435681728384565,0.8918871767964626,0.8918871767964626,1.845327416780985,25,0,0,3.9434082031250073
> AAAGTAGAGCCGGTAA-1,9,143738,1747,13705,2843,125443,0.019779042424411083,0.006124784111804904,41,0.29841323168725303,0.29841323168725303,0.9805536203473828,0.9805536203473828,1.8488553571803503,23,0,0,5.741357421875011
> AAAGTAGCATCCACGG-1,10,219044,2334,21335,4367,191008,0.019936633735687808,0.009352377729667244,62,0.2219555930296248,0.2219555930296248,0.886119897530825,0.886119897530825,1.8399759257056079,-3,0,0,3.326074218750006
> AAAGTAGTCTGTATGG-1,11,201076,2412,17130,3877,177657,0.01928126678469832,0.008577818468292442,58,0.23192375930546155,0.23192375930546155,0.8987765062553958,0.8987765062553958,1.8695655216819238,5,0,0,3.6129394531250063
> AAAGTAGTCTTCACGC-1,12,306588,2728,29061,5802,268997,0.018924419742455675,0.013065888084613456,87,0.1855875456556801,0.1855875456556801,0.8651298666321601,0.8651298666321601,1.8871088528215787,4,0,0,2.4009277343750037
> AAATGCCTCTGCTACC-1,13,388508,3762,37700,7592,339454,0.019541425144398567,0.01658867741062077,110,0.18862021146234528,0.18862021146234528,0.9791540468075924,0.9791540468075924,1.9183010653339494,-2,0,0,2.490820312500004
> AACCATGCAACGCGTC-1,14,252458,2877,26803,4459,218319,0.017662343835410245,0.01063741764388676,71,0.19531869262779145,0.19531869262779145,0.8302301340525406,0.8302301340525406,3.3243457018262252,17,0,0,2.895605468750005
> AACCATGCATGAATGA-1,15,73548,1256,6019,1509,64764,0.020517213248490783,0.0030901137268241137,21,0.3967454164992783,0.3967454164992783,0.9496714389706746,0.9496714389706746,1.8451671145448438,17,0,0,9.616601562500023
> AACGTTGAGAAACCAT-1,16,88244,745,9669,1611,76219,0.018256198721726125,0.0038033315218422275,25,0.3100328286434906,0.3100328286434906,0.7943890490416823,0.7943890490416823,1.8477014912839318,24,0,0,6.084472656250012
> ```

Dear Romeo,

Thank you for the wait. I have checked and that happens to be the thresholds are too stringent for your data. If you set it to a lower threshold and you could retain more results:

![image](https://user-images.githubusercontent.com/5945741/202698068-25419caf-1481-43f4-8519-e4d3dc63955e.png)

I have now also change the threshold default values to 25% of the variable data quantile, so that more data can be retained.

Best,
Lu
